Add ARIA DevTools
brunopulis/awesome-a11y pull request #130
Opened 2020-10-28 17:21 UTC by ziolko

This is a request to add my open-source browser extension that recently got some positive feedback from early users: https://chrome.google.com/webstore/detail/aria-devtools/dneemiigcbbgbdjlcdjjnianlikimpck

2020-10-29 16:27 UTC, brunopulis commented
@ziolko awesome work! <3

2020-10-29 16:29 UTC, brunopulis requested changes
@ziolko could you include the link in alphabetical order to keep the information consistent?

2020-10-29 21:11 UTC, ziolko commented
@brunopulis thanks! I've moved the tool to the right place on this list.

2020-10-30 22:45 UTC, brunopulis approved these changes

2020-10-30 22:46 UTC, merged